### PR TITLE
Replacement fix

### PR DESCRIPTION
**Pull request by Joshix-1**
This now doesn't use recursion.
When using replace_ignorecase now multiple instances get replaced

(This could lead to an infinite loop, as the recursion one lead to infinite recursion)
.

### CODE REVIEW

**Comment by TheDarkBug** [comment]
Ok it now works on my amd PC, but I still get the segfault on my Intel laptop

**Comment by Joshix-1** [comment]
I think I know the problem:
When cpu gets replaced with CPUwU the string still contains cpu (ignoring case).

**Comment by TheDarkBug** [comment]
Yes that's it (sorry for using this pr to test things, but I am too lazy to make a new branch)

**Comment by Joshix-1** [comment]
I think you need to do the same for the gpu and apple replacements

**Pull request merged**
