### PR TITLE
macOS fixes

### PR DESCRIPTION
**Pull request by mTvare6**
In the current code you are listing all formula available in brew repo instead of checking installed

### CODE REVIEW

**Comment by TheDarkBug** [comment]
Ah finally, thanks

**Comment by sech1p** [comment]
It returns me `32767` (max value of 16-bit integer) packages, however, I had only 232 👀

**Comment by TheDarkBug** [comment]
> It returns me `32767` (max value of 16-bit integer) packages, however, I had only 232 👀

Well, I think we can reopen #81

**Comment by mTvare6** [comment]
@TheDarkBug
image

**Pull request merged**
