### PR TITLE
fix replacing ignorecase with multiple things to replace

### PR DESCRIPTION
**Pull request by Joshix-1**

### CODE REVIEW

**Comment by TheDarkBug** [comment]
Line [741](https://github.com/TheDarkBug/uwufetch/pull/138/files#diff-f8d0e9274ee0478c76f2789f7cb60e73656e1a0b3890425b27314c6e2ce71914R741) causes a segfault (I think because the function returns itself), please fix this.

**Comment by Joshix-1** [comment]
The replace function also uses recursion. On my system the pr worked. Without the recursion I don't think the problem is fixed, but I need to try it.

**Comment by TheDarkBug** [comment]
On both my PCs it works, I will try it also on a vm, just to be sure

**Comment by Joshix-1** [comment]
The problem is that it doesn't replace multiple instances of the word. In my GPU info there is two times "Radeon" it only replaces the first one.

**Comment by Joshix-1** [comment]
How did you get the segfault?

**Comment by Joshix-1** [comment]
https://github.com/Joshix-1/uwufetch/blob/replacement-fix/uwufetch.c#L727-L743 works for me.

**Comment by TheDarkBug** [comment]
According to gdb it calls [`replace_ignorecase`](https://github.com/Joshix-1/uwufetch/blob/replacement-fix/uwufetch.c#L742) endlessly

**Comment by Joshix-1** [comment]
What's the string? 
The following check should prevent the infinite recursion, like the similar check in the replace function should.
```c
if (!(ch = strcasestr(original, search)))
    return;
```

**Pull request merged**
