### PR TITLE
add missing macOS mentions in docs + add Windows support (currently Cygwin-only)

### PR DESCRIPTION
**Pull request by sech1p**
windows in action:
image

uwufetch for vanilla Windows should works after replacing all `iscygwin`/Windows-related phrases to fetching by `wmic` (because fetching the used ram amount by windows api is a pain)

### CODE REVIEW

**Comment by TheDarkBug** [comment]
I just installed cygwin (didn't even know it exixted), but I have no idea on how am I supposed to compile it: `cygwin`, `cygwin32` and `cygwin-devel` are installed, but all `sys/` includes do not work, even if I add the `-I /usr/includes/` flag. Could you add a new option in the makefile just for windows? Thanks

**Comment by sech1p** [comment]
> I just installed cygwin (didn't even know it exixted), but I have no idea on how am I supposed to compile it: `cygwin`, `cygwin32` and `cygwin-devel` are installed, but all `sys/` includes do not work, even if I add the `-I /usr/includes/` flag. Could you add a new option in the makefile just for windows? Thanks

I will add later because now I do not have access to a Windows computer, although it compiles on msys2 without any problems

**Comment by sech1p** [comment]
> I just installed cygwin (didn't even know it exixted), but I have no idea on how am I supposed to compile it: `cygwin`, `cygwin32` and `cygwin-devel` are installed, but all `sys/` includes do not work, even if I add the `-I /usr/includes/` flag. Could you add a new option in the makefile just for windows? Thanks

it's look like compilation under cygwin doesn't need any modifications

screenshot from fresh cygwin installation (with `gcc`, `make` and `git`):
image

**Comment by TheDarkBug** [comment]
That's awkward, I got lots of errors with the libs, anyway I'll retry tomorrow

**Pull request merged**
